@echo off
REM Generated by agent updater - placeholders filled at write time.
REM
REM KNOWN ACCEPTED LIMITATION (single-shop PC): the "has the agent exited?" wait
REM loop and the rollback taskkill both key on the node.exe IMAGE NAME. On the
REM shop PC the agent is the only node.exe. Do not run this on a machine with
REM other node processes you care about.
REM
REM Sleeps use `ping` rather than `timeout` on purpose: this script is spawned
REM detached with stdio ignored, and `timeout` fails with "input redirection is
REM not supported" when stdin is not a console.
REM
REM This script runs as its OWN one-shot scheduled task ("SelfPrintUpdater"),
REM NOT as a child of the agent: `schtasks /End /TN SelfPrintAgent` terminates
REM that task's whole job object, and a detached child would be killed with it.
REM Every exit path best-effort deletes SelfPrintUpdater so the task list stays
REM clean; deleting a still-running one-shot task does not stop this process.
REM
REM INVARIANT: every failure branch must leave a working agent installed and
REM restart the scheduled task.
set "ROOT={{ROOT}}"
set "KIND={{KIND}}"
set "TARGET={{VERSION}}"
set "LOG=%ROOT%\update-staging\updater.log"

REM Never hold a directory handle inside engine\ - the agent's cwd is
REM <root>\engine, and an inherited cwd there makes every full-kind rmdir/ren of
REM engine\ fail. Park at %ROOT% deterministically.
cd /d "%ROOT%"

echo [%date% %time%] updater start kind=%KIND% target=%TARGET% >> "%LOG%"

REM 0. Stop the scheduled task FIRST. START-PRINTER.bat wraps `npm run agent` in
REM an infinite restart loop, so killing node alone just makes the wrapper
REM relaunch it 5s later - the wait loop below would never clear, and a
REM relaunched agent would hold engine\ open during the rename. /End kills the
REM whole task process tree (wscript -> cmd wrapper -> node). Both :healthy and
REM :unhealthy /Run the task again, which starts the wrapper fresh.
REM Note: the task is registered with RestartCount 999, which only restarts a
REM task that FAILED; /End is a normal stop, so it does not fight us here.
schtasks /End /TN "SelfPrintAgent" >nul 2>nul

REM 1. Belt and braces: wait (max 60s) for the agent's node process to exit and
REM release engine\ files.
set /a tries=0
:waitloop
tasklist /FI "IMAGENAME eq node.exe" 2>nul | find /I "node.exe" >nul
if errorlevel 1 goto prep
set /a tries+=1
if %tries% geq 60 (
  echo [%time%] agent never exited, aborting swap >> "%LOG%"
  echo agent process did not exit within 60s> "%ROOT%\update-rollback.txt"
  schtasks /Run /TN "SelfPrintAgent" >nul 2>nul
  schtasks /Delete /TN "SelfPrintUpdater" /F >nul 2>nul
  exit /b 1
)
ping -n 2 127.0.0.1 >nul
goto waitloop

:prep
REM Clear a stale backup left by a hard crash mid-swap, but ONLY when the live
REM install is intact - otherwise the backup is the last good copy.
if exist "%ROOT%\engine\agent\version.json" (
  if exist "%ROOT%\engine.bak" rmdir /S /Q "%ROOT%\engine.bak" >nul 2>nul
  if exist "%ROOT%\engine\agent.bak" rmdir /S /Q "%ROOT%\engine\agent.bak" >nul 2>nul
)

:swap
del "%ROOT%\agent-health.txt" >nul 2>nul
if "%KIND%"=="full" (
  ren "%ROOT%\engine" engine.bak || goto swapfail
  xcopy "%ROOT%\update-staging\payload" "%ROOT%\engine\" /E /I /Q /Y >nul || goto restorefull
  copy /Y "%ROOT%\engine.bak\agent\config.json" "%ROOT%\engine\agent\config.json" >nul || goto restorefull
) else (
  ren "%ROOT%\engine\agent" agent.bak || goto swapfail
  xcopy "%ROOT%\update-staging\payload\agent" "%ROOT%\engine\agent\" /E /I /Q /Y >nul || goto restorecode
  copy /Y "%ROOT%\engine\agent.bak\config.json" "%ROOT%\engine\agent\config.json" >nul || goto restorecode
)

echo [%time%] swap done, restarting task >> "%LOG%"
schtasks /Run /TN "SelfPrintAgent" >nul 2>nul

REM 2. Wait up to 90s for the new agent's health heartbeat with the target version.
set /a tries=0
:healthloop
if exist "%ROOT%\agent-health.txt" (
  REM /X = whole-line match, so target 1.1 does not match a 1.1.5 heartbeat.
  findstr /X /C:"%TARGET%" "%ROOT%\agent-health.txt" >nul && goto healthy
)
set /a tries+=1
if %tries% geq 90 goto unhealthy
ping -n 2 127.0.0.1 >nul
goto healthloop

:healthy
echo [%time%] new agent healthy, removing backup >> "%LOG%"
if "%KIND%"=="full" ( rmdir /S /Q "%ROOT%\engine.bak" ) else ( rmdir /S /Q "%ROOT%\engine\agent.bak" )
rmdir /S /Q "%ROOT%\update-staging\payload" >nul 2>nul
schtasks /Delete /TN "SelfPrintUpdater" /F >nul 2>nul
exit /b 0

:unhealthy
echo [%time%] no heartbeat in 90s, rolling back >> "%LOG%"
REM Stop the task again (:swap restarted it, so the wrapper loop is alive and
REM would relaunch node the moment we kill it), then kill the stuck agent and
REM give Windows/AV a beat to drop file handles before deleting.
schtasks /End /TN "SelfPrintAgent" >nul 2>nul
taskkill /IM node.exe /F >nul 2>nul
ping -n 3 127.0.0.1 >nul

REM Retry the delete+restore: a lingering handle can make rmdir fail partially,
REM and a failed ren would otherwise leave the half-deleted new tree in place
REM while the good copy sits in .bak.
set /a rb=0
:rollbackloop
if "%KIND%"=="full" (
  rmdir /S /Q "%ROOT%\engine" >nul 2>nul
  ren "%ROOT%\engine.bak" engine >nul 2>nul
) else (
  rmdir /S /Q "%ROOT%\engine\agent" >nul 2>nul
  ren "%ROOT%\engine\agent.bak" agent >nul 2>nul
)
REM Done only when the live install is back AND no backup is left behind.
if exist "%ROOT%\engine\agent\version.json" (
  if not exist "%ROOT%\engine.bak" if not exist "%ROOT%\engine\agent.bak" goto rollbackdone
)
set /a rb+=1
if %rb% geq 5 goto rollbackfailed
echo [%time%] rollback attempt %rb% incomplete, retrying >> "%LOG%"
ping -n 3 127.0.0.1 >nul
goto rollbackloop

:rollbackdone
echo [%time%] rollback complete, previous version restored >> "%LOG%"
echo new agent failed health check within 90s> "%ROOT%\update-rollback.txt"
schtasks /Run /TN "SelfPrintAgent" >nul 2>nul
schtasks /Delete /TN "SelfPrintUpdater" /F >nul 2>nul
exit /b 1

:rollbackfailed
echo [%time%] ROLLBACK FAILED - manual recovery needed >> "%LOG%"
echo [%time%] previous version is still in engine.bak or engine\agent.bak >> "%LOG%"
echo ROLLBACK FAILED - manual recovery needed: previous version is in engine.bak or engine\agent.bak> "%ROOT%\update-rollback.txt"
schtasks /Run /TN "SelfPrintAgent" >nul 2>nul
schtasks /Delete /TN "SelfPrintUpdater" /F >nul 2>nul
exit /b 2

:restorefull
echo [%time%] full swap failed, restoring engine.bak >> "%LOG%"
rmdir /S /Q "%ROOT%\engine" >nul 2>nul
ren "%ROOT%\engine.bak" engine
goto swapfail2
:restorecode
echo [%time%] code swap failed, restoring agent.bak >> "%LOG%"
rmdir /S /Q "%ROOT%\engine\agent" >nul 2>nul
ren "%ROOT%\engine\agent.bak" agent
goto swapfail2
:swapfail
echo [%time%] rename failed >> "%LOG%"
:swapfail2
echo file swap failed, restored previous version> "%ROOT%\update-rollback.txt"
schtasks /Run /TN "SelfPrintAgent" >nul 2>nul
schtasks /Delete /TN "SelfPrintUpdater" /F >nul 2>nul
exit /b 1
